version: 0.2

phases:
  install:
    commands:
      - npm install
    runtime-versions:
      nodejs: 12
  build:
    commands:
      - npm start
artifacts:
      files:
        - index.js
        - package.json
