version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
  build:
    commands:
      - npm install
      - npm run build
  post_build:
    commands:
      - npm start
artifacts:
      files:
        - '**/*'
