export const SERVER_URL = `${process.env.SERVER_URL || 'http://localhost:3317'}`;
export const ITEMS_PER_PAGE = 16;
export const BETS_PER_PAGE = 10;
export const SUBS_PER_PAGE = 10;
export const FILTERS_PER_PAGE = 40;
export const UPLOAD_FILES_LIMIT = 8;
export const CONFIRM_SECONDS = 120;
export const TEXT_LIMIT = 3000;
export const TITLE_LIMIT = 50;