export const Facebook = `/icons/fb_icon.svg`;
export const Instagram = `/icons/instagram_icon.svg`;
export const Youtube = `/icons/youtube_icon.svg`;
export const Twitter = `/icons/tw_icon.svg`;
export const Whatsapp = `/icons/wp_icon.svg`;
export const Telegram = `/icons/tg_icon.svg`;
export const PlIcon = `/icons/place_icon.svg`;
export const CategoryIcon = `/icons/kat_icon.svg`;
export const SearchIcon = `/icons/sr_icon.svg`;
export const SignIcon = `/icons/sign_icon.svg`;
export const AddIcon = `/icons/add.svg`;
export const Electronica = `/icons/elektronika_optim_fin.svg`;
export const KrasotaZdorovye = `/icons/krasota_zdorovye_optim_fin.svg`;
export const Mebel = `/icons/mebel_optim_fin.svg`;
export const TelefonPlanshet = `/icons/tel_plansh_optim_fin.svg`;
export const KompTexnika = `/icons/komp_tehnika_optim_fin.svg`;
export const JenskiyGarderob = `/icons/jenskiy_garderob_optim_fin.svg`;
export const UslugiOptom = `/icons/uslugi_optim_fin.svg`;
export const OtdixOptom = `/icons/otdih_optim_fin.svg`;
export const DownArrowIcon = `/icons/down-arrow.svg`;
export const FilterIcon = `/icons/filter_icon.svg`;
export const RightArrow = `/icons/right_arrow.svg`;
export const SafeBuyingIcon = `/icons/safe_buying.svg`;
export const SafeBuyingIcon2 = `/icons/safe_buying2.svg`;
export const AdvertisementIcon = `/icons/ads_icon.svg`;
export const TorgIcon = `/icons/torg_icon.svg`;
export const RatingIcon = `/icons/rating_icon.svg`;
export const BackSpaceArrow = `/icons/back_space_arrow.svg`;
export const ShareIcon = `/icons/share-icon.svg`;
export const DownArrow = `/icons/down_arrow.svg`;
export const HeartIcon = `/icons/heart_icon.svg`;
export const ComplainIcon = `/icons/complain_icon.svg`;
export const UserAvatar = `/icons/user-avatar_icon.svg`;
export const StarIcon = `/icons/star_icon.svg`;
export const FullscreenIcon = `/icons/fullscreen-icon.svg`;
export const FullscreenIcon2 = `/icons/fullscreen-icon2.svg`;
export const Subscribe_icon = `/icons/touch_icon.svg`;
export const SpeakerNotes_icon = `/icons/speaker_notes.svg`;
export const Bonus_icon = `/icons/bonus_icon.svg`;
export const Auto_view_icon = `/icons/auto_view_icon.svg`;
export const Auto_icon = `/icons/auto_icon.svg`;
export const Wheel_icon = `/icons/wheel_icon.svg`;
export const Info_icon = `/icons/info_icon.svg`;

// Custom svgs
export { ButtonCloseIcon } from './close_icon/CloseIcon';
export { PrevArrowIcon } from './prev_arrow_icon/PrevArrowIcon';
export { BusinessIcon } from './BusinessIcon';
export { StoreIcon } from './StoreIcon';
export { QuestionIcon } from './QuestionIcon';
export { LocationIcon } from './LocationIcon';
export { FavoriteIcon } from './FavoriteIcon';
export { FavoriteBorderIcon } from './FavoriteBorderIcon';
export { DeliveryIcon } from './DeliveryIcon';
export { SafeIcon } from './SafeIcon';
export { SwapIcon } from './SwapIcon';
export { LockIcon } from './LockIcon';
export { MegaphoneIcon } from './MegaphoneIcon';
export { RaiseToTopIcon } from './RaiseToTopIcon';
export { PromoteIcon } from './PromoteIcon';
export { DoubleUpIcon } from './DoubleUpIcon';
export { SettingsIcon } from './SettingsIcon';
export { EyeIcon } from './EyeIcon';
export { RestoreIcon } from './RestoreIcon';
export { DoneAllIcon } from './DoneAllIcon';
export { CloseIcon } from './CloseIcon';
export { CameraIcon } from './CameraIcon';
export { Logo } from './logo/Logo';
export { PhoneIcon } from './PhoneIcon';
export { SurpriseIcon } from './SurpriseIcon';
export { SubstractIcon } from './SubstractIcon';
export { Search_icon } from './SearchIcon';
export { LetterIcon } from './LetterIcon';
export { NotificationIcon } from './NotificationIcon';
export { AnimalsIcon } from './category_icons/AnimalsIcon';
export { ApartmentsIcon } from './category_icons/ApartmentsIcon';
export { CarIcon } from './category_icons/CarIcon';
export { ElectronicIcon } from './category_icons/ElectronicIcon';
export { ForFreeIcon } from './category_icons/ForFreeIcon';
export { HangerIcon } from './category_icons/HangerIcon';
export { OtherIcon } from './category_icons/OtherIcon';
export { HobbyIcon } from './category_icons/HobbyIcon';
export { PartsIcon } from './category_icons/PartsIcon';
export { JobIcon } from './category_icons/JobIcon';
export { ServicesIcon } from './category_icons/ServicesIcon';
export { SofaIcon } from './category_icons/SofaIcon';
export { SpecTechIcon } from './category_icons/SpecTechIcon';
export { BackspaceIcon } from './BackspaceIcon';
export { Car } from './site_map_icons/Car';
export { Job } from './site_map_icons/Job';
export { Animals } from './site_map_icons/Animals';
export { Estate } from './site_map_icons/Estate';
export { Free } from './site_map_icons/Free';
export { Goods } from './site_map_icons/Goods';
export { Hobby } from './site_map_icons/Hobby';
export { Home } from './site_map_icons/Home';
export { Motorcycle } from './site_map_icons/Motorcycle';
export { Other } from './site_map_icons/Other';
export { Phone } from './site_map_icons/Phone';
export { Service } from './site_map_icons/Service';
export { Hacker } from './Hacker';
